on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-app:
    name: Build app
    runs-on: ubuntu-latest
    env:
      androidArch: x86_64
    steps:
      - name: Check out repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: true

      - name: Validate gradle wrapper checksum
        uses: gradle/actions/wrapper-validation@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Set up JDK 21
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          cache-dependency-path: rcbridge/go.sum
          go-version-file: rcbridge/go.mod

      - name: Get NDK version
        id: get_version
        shell: bash
        run: |
          sed -nr \
              -e 's/^\s*(compileSdk)\s*(=)\s([0-9]+).*$/\1\2\3/p' \
              -e 's/^\s*(ndkVersion)\s*(=)\s"(.+)".*$/\1\2\3/p' \
              app/build.gradle.kts \
              >> "${GITHUB_OUTPUT}"

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: AVD cache
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ steps.get_version.outputs.compileSdk }}-${{ env.androidArch }}

      - name: Create AVD snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@b530d96654c385303d652368551fb075bc2f0b6b # v2.35.0
        with:
          # TODO: Remove after Google publishes AOSP-based image.
          target: google_apis
          api-level: ${{ steps.get_version.outputs.compileSdk }}
          arch: ${{ env.androidArch }}
          ndk: ${{ steps.get_version.outputs.ndkVersion }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Build and test
        uses: reactivecircus/android-emulator-runner@b530d96654c385303d652368551fb075bc2f0b6b # v2.35.0
        with:
          # TODO: Remove after Google publishes AOSP-based image.
          target: google_apis
          api-level: ${{ steps.get_version.outputs.compileSdk }}
          arch: ${{ env.androidArch }}
          ndk: ${{ steps.get_version.outputs.ndkVersion }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          # Debug build only since release builds require a signing key
          script: ./gradlew --no-daemon build connectedDebugAndroidTest -x assembleRelease
